server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:sqlserver://LEONW10;databaseName=registration_v2
    username: user_001
    password: Password1!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        show_sql: true
        ddl-auto: none #create-drop
        generate-ddl: true
        hbm2ddl:
          auto: create
